name: Build

on: push

jobs:
  build-ubuntu:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install OBS
        run: |
          sudo add-apt-repository ppa:obsproject/obs-studio
          sudo apt update
          sudo apt install -y obs-studio
      - name: Build
        run: |
          cp /usr/lib/libobs.so ./
          go build -buildmode=c-shared -o obs-studio-exporter.so
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: obs-studio-exporter-ubuntu
          path: obs-studio-exporter.so

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install OBS
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://cdn-fastly.obsproject.com/downloads/OBS-Studio-26.1.1-Full-Installer-x64.exe" -OutFile obs-studio-installer.exe
          .\obs-studio-installer.exe /S | Out-Null
      - name: Build
        shell: pwsh
        run: |
          Copy-Item "C:\\Program Files\\obs-studio\\bin\\64bit\\obs.dll" -Destination "."
          go build -buildmode=c-shared -o obs-studio-exporter.dll
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: obs-studio-exporter-windows
          path: obs-studio-exporter.dll

  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install OBS
        run: |
          curl -L -o obs-mac.dmg "https://cdn-fastly.obsproject.com/downloads/obs-mac-26.1.2.dmg"
          hdiutil attach ./obs-mac.dmg
      - name: Build
        run: |
          cp /Volumes/OBS*/OBS.app/Contents/Frameworks/libobs.0.dylib ./libobs.0.dylib
          go build -buildmode=c-shared -o obs-studio-exporter.so
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: obs-studio-exporter-macos
          path: obs-studio-exporter.so

